baseurl      = 'https://www.bitbitking.com'
title        = 'BBK'
languageCode = 'en-us'
theme        = 'hello-friend-ng'
paginate     = 10
defaultContentLanguage = 'zh-cn'
defaultContentLanguageInSubdir = true


googleAnalytics = 'G-2G8PSM72ZC'

[params]
  dateform        = 'Jan 2, 2006'
  dateformShort   = 'Jan 2'
  dateformNum     = '2006-01-02'
  dateformNumTime = '2006-01-02 15:04'


  # Subtitle for home
  homeSubtitle = 'All about Cryptos and Web3'

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = true

  # Metadata mostly used in document's head
  # description = 'BitBitKing's blog'
  keywords = 'BitBitKing, BBK, blog, web3, crypto, blockchain, nft, dao, exchange, cryptocurrency, cryptocurrencies, gamefi, defi'
  images = ['']

[taxonomies]
    category = 'categories'
    tag      = 'tags'
    series   = 'series'



  [languages]
  [languages.zh-cn]
    title = 'Welcome to the World of Web3'
    contentDir = 'content/'
    hasCJKLanguage = true
    languageName = '中文'

   [[languages.zh-cn.menu.main]]
     name = '工具'
     url = 'https://bitbitking.notion.site/World-of-Web3-563fc1050fcc4de19dc9926399dcbc45'
     weight = 10
   [[languages.zh-cn.menu.main]]
     name = '文章'
     url = 'posts'
     weight = 20
   [[languages.zh-cn.menu.main]]
     name = '关于'
     url = 'about'
     weight = 30
   [[languages.zh-cn.menu.main]]
     name = '联系'
     url = 'contact'
     weight = 40

   [languages.zh-cn.params]
   subtitle = 'All about Cryptos and Web3'
   description = 'BitBitKing - All about Cryptos, Blockchains and Web3'
   readOtherPosts = '阅读更多'

   #[languages.zh-cn.params.logo]
   #   logoText = 'BBK'
   #   logoCursorColor = '#f09e38'

  [languages.en]
    title = 'Welcome to the World of Web3'
    contentDir = 'content/en/'
    languageName = 'English'

   [[languages.en.menu.main]]
     name = 'Tools'
     url = 'https://bitbitking.notion.site/World-of-Web3-563fc1050fcc4de19dc9926399dcbc45'
     weight = 10
   [[languages.en.menu.main]]
     name = 'Blog'
     url = 'en/posts'
     weight = 20
   [[languages.en.menu.main]]
     name = 'About'
     url = 'en/about'
     weight = 30
   [[languages.en.menu.main]]
     name = 'Contact'
     url = 'en/contact'
     weight = 40

    

    [languages.en.params]
    subtitle = 'All about Cryptos and Web3'
    description = 'BitBitKing - All about Cryptos, Blockchains and Web3'
    readOtherPosts = 'Read other posts'

   # [languages.en.params.logo]
   #   logoHomeLink = '/en'
   #   logoText = 'BBK'
   #   logoCursorColor = '#f09e38'
   # or
   #
   # path = '/img/your-example-logo.svg'
   # alt = 'Your example logo alt text'


	 # And you can even create generic menu
	 #[[menu.main]]
	 #   identifier = 'blog'
	 #   name       = 'Blog'
	 #   url        = '/posts'

  [params.logo]
  #  logoMark     = '>'
    logoText     = 'BBK '
    logoCursorColor    = '#f09e38'
 #   logoCursorAnimate  = '1s'
 #   logoCursorPathname = true


  [[params.social]]
  name = 'youtube'
  url = 'https://www.youtube.com/c/BitBitKing/?sub_confirmation=1'

  [[params.social]]
  name = 'twitter'
  url = 'https://twitter.com/BitBitKing2022'

  [[params.social]]
  name = 'instagram'
  url = 'https://instagram.com/bitbitking'

  [[params.social]]
  name = 'facebook'
  url = 'https://www.facebook.com/BitBitKing2000'

  [[params.social]]
  name = 'github'
  url = 'https://github.com/BitBitKing'

  [[params.social]]
  name = 'email'
  url = 'mailto:bitbitking2020@gmail.com'

  [[params.social]]
  name = 'medium'
  url = 'https://medium.com/@bitbitking'

  [[params.social]]
  name = 'wow3'
  url = 'https://bitbitking.notion.site/bitbitking/World-of-Web3-563fc1050fcc4de19dc9926399dcbc45'